# 基础设置
base:
  # 获取天气的城市
  city: 北京
  guide: true

# 服务器配置
server:
  # 启动地址（仅用于控制台输出）
  # auto 为自动获取IP地址
  host: auto
  # 启动端口号
  port: 50831
  # 是否需要拼接端口号
  splicePort: true
  # 当host为auto时，是否在使用"#锅巴登录"时显示所有IP地址
  showAllIp: false

# jwt配置
jwt:
  # JWT 秘钥（随机生成，非必要请勿修改！）
  secret: ""
